---
title: "noduleEDA"
author: "Alexander Romanus"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mlbench)
library(dplyr)
library(caret)
library(Hmisc)
library(corrplot)
library(tidyverse)
library(pracma)
library(pROC)
library(gridExtra)
annotationData <- read.csv("../Data/Meta/meta_annotation_info_train.csv")
```

``` {r get-train-data, include=FALSE}
# Using patient and nodule ids from training dataset in nodule csv file to subset rows of annotation csv to prevent data leakage
train <- read.csv("../Data/Meta/meta_annotation_info_train.csv", header = TRUE)
test <- read.csv("../Data/Meta/meta_annotation_info_test.csv", header = TRUE)

# eliminate all columns that have to do with Malignancy and the response var

non_train_columns = c("Patient_id", "Nodule_no", "Nodule_id", "Annotation_no", "Malignancy_median", "Malignancy_median_high", "Malignancy_entropy",
                      "Malignancy_mode", "Malignancy_mean", "Malignancy")

train_filter <- train[!(names(train) %in% non_train_columns)]

test_filter <- test[!(names(test) %in% non_train_columns)]

```

```{r get-dataframe-covariates-response}
annotation1 <- train %>% filter(Annotation_no == "1")
annotation2 <- train %>% filter(Annotation_no == "2")
annotation3 <- train %>% filter(Annotation_no == "3")
annotation4 <- train %>% filter(Annotation_no == "4")

annotation1 <- annotation1 %>% select(Internal.structure, Calcification, Subtlety,	Margin,	Sphericity,	Lobulation,	Spiculation,	Texture, Malignancy)
annotation2 <- annotation2 %>% select(Internal.structure, Calcification, Subtlety,	Margin,	Sphericity,	Lobulation,	Spiculation,	Texture, Malignancy)
annotation3 <- annotation3 %>% select(Internal.structure, Calcification, Subtlety,	Margin,	Sphericity,	Lobulation,	Spiculation,	Texture, Malignancy)
annotation4 <- annotation4 %>% select(Internal.structure, Calcification, Subtlety,	Margin,	Sphericity,	Lobulation,	Spiculation,	Texture, Malignancy)
```

``` {r covariates-annotation-EDA}
annotationDataAnalysis <- function(annData1, annData2, annData3, annData4) {
  categoricalColumns <- colnames(annData1)
  k <- length(annData1)
  
  for(j in 1:k) {
    options(repr.plot.width=4, repr.plot.height=5)
    plot1 <- ggplot(annData1, aes(x=as.factor(annData1[, j]))) + geom_bar(fill = "red", position = position_dodge(preserve = "total")) + labs(x = colnames(annData1[j])) + scale_x_discrete(drop=FALSE)
    plot2 <- ggplot(annData2, aes(x=as.factor(annData2[, j]))) + geom_bar(fill = "blue", position = position_dodge(preserve = "total")) + labs(x = colnames(annData2[j])) + scale_x_discrete(drop=FALSE)
    plot3 <- ggplot(annData3, aes(x=as.factor(annData3[, j]))) + geom_bar(fill = "green", position = position_dodge(preserve = "total")) + labs(x = colnames(annData3[j])) + scale_x_discrete(drop=FALSE)
    plot4 <- ggplot(annData4, aes(x=as.factor(annData4[, j]))) + geom_bar(fill = "orange", position = position_dodge(preserve = "total")) + labs(x = colnames(annData4[j])) + scale_x_discrete(drop=FALSE)
    ggsave(filename = paste("Plots/", categoricalColumns[j], "_annotation_comparisons.png", sep=""), grid.arrange(plot1, plot2, plot3, plot4, nrow=4))
  }
}

annotationDataAnalysis(annotation1, annotation2, annotation3, annotation4)
```

```{r predictors-distributions-by-response-value, fig.height=15, fig.width=15}
summary(train)
varnames = names(train)
par(mfrow=c(3,3))
for(j in c(4:11))
{ plot(factor(train$Is_cancer),train[,j],xlab="Is_cancer",ylab=varnames[j]) }
par(mfrow=c(3,3))
for(j in c(12:19))
{ plot(factor(train$Is_cancer),train[,j],xlab="Is_cancer",ylab=varnames[j]) }
par(mfrow=c(3,3))
for(j in c(21:28))
{ plot(factor(train$Is_cancer),train[,j],xlab="Is_cancer",ylab=varnames[j]) }
par(mfrow=c(3,3))
for(j in c(30:37))
{ plot(factor(train$Is_cancer),train[,j],xlab="Is_cancer",ylab=varnames[j]) }
par(mfrow=c(3,3))
for(j in c(39:46))
{ plot(factor(train$Is_cancer),train[,j],xlab="Is_cancer",ylab=varnames[j]) }
par(mfrow=c(3,3))
for(j in c(48:55))
{ plot(factor(train$Is_cancer),train[,j],xlab="Is_cancer",ylab=varnames[j]) }
for(j in c(56:57))
{ plot(factor(train$Is_cancer),train[,j],xlab="Is_cancer",ylab=varnames[j]) }
```


